# -*- coding: utf-8 -*-
"""Titanicdt

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fuRmo5Cx8JUIe36ga3Vdg1w19LzztnR8
"""

#Loading Dataset
import pandas as pd
import matplotlib.pyplot as plt
url="https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv"
df=pd.read_csv(url)
df.head()

df.tail()

#Finding Rows and Columns
df.shape

#Statistical Outcome
df.describe()

#Finding Missing Values
df.isnull().sum()

#Identifying the datatypes of each columns
df.dtypes

print(df.columns.tolist())

#Identifying the count of Survived Passangers
# 0 means death 1 means Suriviving
df['Survived'].value_counts()

#Survival Rate
survival_rate = df['Survived'].mean() * 100
print(f"Survival Rate: {survival_rate:.1f}%")

#Identifying the count of PassengerClass
df['Pclass'].value_counts()

# Handling Missing Values
df=df.drop("Cabin",axis=1)

df.head()

#filling the missing values of Age with median
df['Age'] = df['Age'].fillna(df['Age'].median())

#Filling the Missing value of Embarked with Mode
df['Embarked'] = df['Embarked'].fillna(df['Embarked'].mode()[0])

#After Filling Null Values Checking again if null values appears
df.isnull().sum()

#plotting boxplot for Numerical Columns
numeric_cols = ['Age', 'Fare', 'SibSp', 'Parch']
for col in numeric_cols:
  plt.figure(figsize=(6,2))
  plt.boxplot(df[col])
  plt.title(f'Boxplot of {col}')
  plt.show()

plt.figure(figsize=(6,3))
plt.hist(df['Fare'],bins=30,color='blue',edgecolor='black')
plt.title("Fare Distribution")
plt.xlabel("Fare")
plt.ylabel("Count")
plt.show()

#Identifying the Outliers
numeric_cols = ['Age', 'Fare', 'SibSp', 'Parch']
for col in numeric_cols:
  Q1=df[col].quantile(0.25)
  Q3=df[col].quantile(0.75)
  IQR=Q3-Q1
  lower_bound=Q1-1.5*IQR
  upper_bound=Q3+1.5*IQR
  outliers=df[(df[col]<lower_bound) | (df[col]>upper_bound)]
  print(f'Number of outliers in {col}: {len(outliers)}')

#Relationship between Age and fare before Clipping
plt.scatter(df['Age'], df['Fare'], alpha=0.5)
plt.title('Age vs Fare — Before Clipping')
plt.xlabel('Age')
plt.ylabel('Fare')
plt.show()

#Plotting Barplot
df['Survived'].value_counts().plot(kind='bar',color=['yellow','Red'])
plt.title("Survived vs Non_survived")
plt.xlabel("Survived (0=no,1=yes)")
plt.ylabel("Count")
plt.show()

#plotting Histogram
plt.figure(figsize=(6,3))
plt.hist(df['Age'],bins=30,color='green',edgecolor='black')
plt.title("Age Distribution")
plt.xlabel("Age")
plt.ylabel("Count")
plt.show()

#clipping Outliers
Q1=df['Fare'].quantile(0.25)
Q3=df['Fare'].quantile(0.75)
IQR=Q3-Q1
lower=Q1-1.5*IQR
upper=Q3+1.5*IQR
print(lower)
print(upper)
df['Fare']=df['Fare'].clip(lower,upper)

#After Clipping Outliers
plt.figure(figsize=(6,3))
plt.boxplot(df['Fare'])
plt.title("Fare Distribution")
plt.xlabel("Fare")
plt.ylabel("Count")
plt.show()

#Normalizing Age and Fare Column
df['Age_norm']=(df['Age']-df['Age'].min())/(df['Age'].max()-df['Age'].min())
df['Fare_norm'] = (df['Fare'] - df['Fare'].min()) / (df['Fare'].max() - df['Fare'].min())

print(df[['Age', 'Age_norm', 'Fare', 'Fare_norm']].head())

#Relationship between - Fare and Age after Clipping
plt.figure(figsize=(6,4))
plt.scatter(df['Age'], df['Fare'], alpha=0.5)
plt.title('Age vs Fare after Clipping')
plt.xlabel('Age')
plt.ylabel('Fare')
plt.show()

#Conclusion
print("Shape:", df.shape)
print("Missing values:", df.isnull().sum().sum())
print("Data is clean and ready! ✅")

# ================================
# CONCLUSIONS — Titanic EDA
# ================================

# 1. DATASET OVERVIEW
#    - 891 passengers, 12 columns
#    - Mix of numerical and categorical data

# 2. MISSING VALUES FOUND & FIXED
#    - Age:     177 missing → filled with median (28.0)
#    - Cabin:   687 missing → dropped (77% missing!)
#    - Embarked:  2 missing → filled with mode (S)

# 3. OUTLIERS FOUND & FIXED
#    - Fare had 116 outliers → clipped at 65.63
#    - Age had 11 outliers
#    - SibSp and Parch also had outliers

# 4. KEY FINDINGS FROM VISUALIZATION
#    - Only 38% of passengers survived
#    - Most passengers were aged 20-35
#    - Fare was heavily right skewed
#    - Age and Fare are weakly correlated

# 5. DATA IS NOW CLEAN & READY
#    - Missing values: 0
#    - Outliers: handled
#    - Numerical columns: normalized